[package]
name = "coin-shuffle-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["all"]
all = ["serde"]
serde = ["dep:serde", "uuid/serde", "rsa/serde"]

[dependencies]
ethers-core = "1.0.2"
serde = { version = "1.0.152", optional = true }
rsa = "0.8.1"
rand = { version = "0.8.5", features = ["getrandom"] }
async-trait = "0.1.64"
thiserror = "1"
tokio = { version = "1.25", features = ["sync", "rt"] }
log = "0.4.17"

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]

[dev-dependencies]
tokio = { version = "1.25", features = ["test-util", "macros"] }
lazy_static = "1.4.0"
