[package]
name = "coin-shuffle-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["all"]
all = ["serde"]
serde = ["dep:serde", "uuid/serde", "rsa/serde"]
    
[dependencies]
ethers-core    = { version = "1.0.2", featores = ["ecdsa"] }
ethers-signers = { version = "1.0.2" }
serde          = { version = "1.0.124", features = ["derive", "rc", "alloc"], optional = true }
rsa            = { version = "0.8.1" }
rand           = { version = "0.8.5" }
async-trait    = { version = "0.1.64" }
uuid           = { version = "1.3.0", features = ["v4", "fast-rng"] }
thiserror      = { version = "1.0.38" }
tokio          = { version = "1.25.0", features = ["full"] }

[profile.dev.package.num-bigint-dig]
opt-level = 3