[package]
name = "coin-shuffle-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["all"]
all = ["serde"]
serde = ["dep:serde", "uuid/serde"]

[dependencies]
ethers = { version = "1.0.2", features = ["rustls"] }
serde = { version = "1.0.152", optional = true }

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]
